"""Seed script to populate the database with sample products."""
import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from app import app
from models import db, Product


PRODUCTS = [
    # ─── Electronics ─────────────────────────────────────
    {
        "name": "Pro Wireless Headphones",
        "price": 149.99,
        "original_price": 199.99,
        "description": "Premium noise-cancelling wireless headphones with 40-hour battery life, ultra-comfortable memory foam ear cups, and studio-quality sound. Features active noise cancellation and transparency mode.",
        "image_url": "/static/images/electronics/pro_wireless_headphones.png",
        "category": "Electronics",
        "rating": 4.8,
        "stock": 25,
        "featured": True,
    },
    {
        "name": "Ultra Smart Watch Pro",
        "price": 299.99,
        "original_price": 399.99,
        "description": "Next-gen smartwatch with AMOLED display, health monitoring, GPS tracking, and 7-day battery life. Water-resistant to 50m with titanium case.",
        "image_url": "/static/images/electronics/ultra_smart_watch_pro.png",
        "category": "Electronics",
        "rating": 4.7,
        "stock": 15,
        "featured": True,
    },
    {
        "name": "Portable Bluetooth Speaker",
        "price": 79.99,
        "original_price": 109.99,
        "description": "Waterproof portable speaker with 360° immersive sound, 24-hour battery, and rugged design. Perfect for outdoor adventures.",
        "image_url": "/static/images/electronics/portable_bluetooth_speaker.png",
        "category": "Electronics",
        "rating": 4.5,
        "stock": 30,
        "featured": False,
    },
    {
        "name": "4K Webcam Pro",
        "price": 129.99,
        "original_price": None,
        "description": "Ultra HD 4K webcam with auto-focus, built-in ring light, and dual microphones. Perfect for streaming and video conferencing.",
        "image_url": "/static/images/electronics/4k_webcam_pro.png",
        "category": "Electronics",
        "rating": 4.3,
        "stock": 20,
        "featured": False,
    },
    {
        "name": "Wireless Charging Dock",
        "price": 39.99,
        "original_price": 59.99,
        "description": "Fast wireless charging dock compatible with all Qi-enabled devices. Sleek aluminum design with LED indicator and overcharge protection.",
        "image_url": "/static/images/electronics/wireless_charging_dock.png",
        "category": "Electronics",
        "rating": 4.4,
        "stock": 50,
        "featured": False,
    },
    {
        "name": "Noise-Cancelling Earbuds",
        "price": 89.99,
        "original_price": 119.99,
        "description": "True wireless earbuds with active noise cancellation, 30-hour battery in the case, and IPX5 water resistance. Rich bass and crystal clear audio.",
        "image_url": "/static/images/electronics/noise-cancelling_earbuds.png",
        "category": "Electronics",
        "rating": 4.6,
        "stock": 35,
        "featured": True,
    },
    {
        "name": "Mechanical Gaming Keyboard",
        "price": 109.99,
        "original_price": 149.99,
        "description": "RGB mechanical keyboard with Cherry MX switches, customizable backlighting, programmable macro keys, and premium aluminum build.",
        "image_url": "/static/images/electronics/mechanical_gaming_keyboard.png",
        "category": "Electronics",
        "rating": 4.5,
        "stock": 18,
        "featured": False,
    },
    {
        "name": "USB-C Hub Adapter",
        "price": 49.99,
        "original_price": None,
        "description": "7-in-1 USB-C hub with HDMI 4K, SD card reader, 3x USB 3.0, and 100W power delivery. Essential for modern laptops.",
        "image_url": "/static/images/electronics/usb-c_hub_adapter.png",
        "category": "Electronics",
        "rating": 4.3,
        "stock": 40,
        "featured": False,
    },
    # ─── Fashion ─────────────────────────────────────────
    {
        "name": "Classic Leather Jacket",
        "price": 189.99,
        "original_price": 249.99,
        "description": "Premium genuine leather jacket with quilted lining, zippered pockets, and a timeless biker design. Available in multiple sizes.",
        "image_url": "/static/images/fashion/classic_leather_jacket.png",
        "category": "Fashion",
        "rating": 4.6,
        "stock": 12,
        "featured": True,
    },
    {
        "name": "Designer Sunglasses",
        "price": 89.99,
        "original_price": 129.99,
        "description": "UV400 polarized sunglasses with titanium frame and scratch-resistant lenses. Classic aviator style with premium carrying case.",
        "image_url": "/static/images/fashion/designer_sunglasses.png",
        "category": "Fashion",
        "rating": 4.5,
        "stock": 35,
        "featured": True,
    },
    {
        "name": "Premium Canvas Sneakers",
        "price": 69.99,
        "original_price": 99.99,
        "description": "Handcrafted canvas sneakers with cushioned insoles, anti-slip rubber soles, and breathable fabric. Minimalist design for everyday wear.",
        "image_url": "/static/images/fashion/premium_canvas_sneakers.png",
        "category": "Fashion",
        "rating": 4.4,
        "stock": 40,
        "featured": False,
    },
    {
        "name": "Minimalist Leather Watch",
        "price": 119.99,
        "original_price": 159.99,
        "description": "Elegant minimalist watch with genuine Italian leather strap, sapphire crystal glass, and Japanese quartz movement.",
        "image_url": "/static/images/fashion/minimalist_leather_watch.png",
        "category": "Fashion",
        "rating": 4.7,
        "stock": 18,
        "featured": True,
    },
    {
        "name": "Wool Blend Overcoat",
        "price": 229.99,
        "original_price": 299.99,
        "description": "Luxurious wool-blend overcoat with satin lining. Tailored fit with notched lapels and double-breasted button closure.",
        "image_url": "/static/images/fashion/wool_blend_overcoat.png",
        "category": "Fashion",
        "rating": 4.6,
        "stock": 10,
        "featured": False,
    },
    {
        "name": "Leather Crossbody Bag",
        "price": 79.99,
        "original_price": 109.99,
        "description": "Compact crossbody bag crafted from full-grain leather. Features adjustable strap, magnetic closure, and multiple compartments.",
        "image_url": "/static/images/fashion/leather_crossbody_bag.png",
        "category": "Fashion",
        "rating": 4.4,
        "stock": 22,
        "featured": False,
    },
    {
        "name": "Cashmere Blend Scarf",
        "price": 59.99,
        "original_price": 89.99,
        "description": "Ultra-soft cashmere blend scarf with fringed edges. Elegant patterns perfect for layering in any season.",
        "image_url": "/static/images/fashion/cashmere_blend_scarf.png",
        "category": "Fashion",
        "rating": 4.3,
        "stock": 28,
        "featured": False,
    },
    # ─── Home & Living ───────────────────────────────────
    {
        "name": "Aromatherapy Diffuser",
        "price": 44.99,
        "original_price": 64.99,
        "description": "Ultrasonic essential oil diffuser with 7 LED color modes, auto shut-off, and whisper-quiet operation. 300ml capacity.",
        "image_url": "/static/images/home/aromatherapy_diffuser.png",
        "category": "Home & Living",
        "rating": 4.5,
        "stock": 30,
        "featured": True,
    },
    {
        "name": "Cozy Throw Blanket",
        "price": 59.99,
        "original_price": None,
        "description": "Luxuriously soft throw blanket made from organic cotton. Perfect for cozy evenings on the couch.",
        "image_url": "/static/images/home/cozy_throw_blanket.png",
        "category": "Home & Living",
        "rating": 4.6,
        "stock": 20,
        "featured": False,
    },
    {
        "name": "Ceramic Plant Pot Set",
        "price": 34.99,
        "original_price": 49.99,
        "description": "Set of 3 modern ceramic plant pots with bamboo trays. Minimalist design with drainage holes. Perfect for succulents.",
        "image_url": "/static/images/home/ceramic_plant_pot_set.png",
        "category": "Home & Living",
        "rating": 4.3,
        "stock": 22,
        "featured": False,
    },
    {
        "name": "Smart LED Desk Lamp",
        "price": 54.99,
        "original_price": 79.99,
        "description": "Adjustable LED desk lamp with touch controls, 5 brightness levels, and 3 color temperatures. Sleek modern design.",
        "image_url": "/static/images/home/smart_led_desk_lamp.png",
        "category": "Home & Living",
        "rating": 4.4,
        "stock": 28,
        "featured": True,
    },
    {
        "name": "Scented Candle Collection",
        "price": 29.99,
        "original_price": 44.99,
        "description": "Set of 4 hand-poured soy wax candles in calming scents: lavender, vanilla, sandalwood, and jasmine. 40-hour burn time each.",
        "image_url": "/static/images/home/scented_candle_collection.png",
        "category": "Home & Living",
        "rating": 4.7,
        "stock": 32,
        "featured": False,
    },
    {
        "name": "Bamboo Serving Tray",
        "price": 24.99,
        "original_price": None,
        "description": "Elegant bamboo serving tray with handles. Perfect for breakfast in bed, entertaining, or decorative display.",
        "image_url": "/static/images/home/bamboo_serving_tray.png",
        "category": "Home & Living",
        "rating": 4.2,
        "stock": 25,
        "featured": False,
    },
    # ─── Sports ──────────────────────────────────────────
    {
        "name": "Performance Running Shoes",
        "price": 129.99,
        "original_price": 169.99,
        "description": "Lightweight performance running shoes with responsive cushioning, breathable mesh upper, and carbon fiber plate. Built for speed.",
        "image_url": "/static/images/sports/performance_running_shoes.png",
        "category": "Sports",
        "rating": 4.7,
        "stock": 20,
        "featured": True,
    },
    {
        "name": "Yoga Mat Premium",
        "price": 49.99,
        "original_price": 69.99,
        "description": "Extra-thick non-slip yoga mat with alignment markers, eco-friendly TPE material, and carrying strap. 6mm cushioning.",
        "image_url": "/static/images/sports/yoga_mat_premium.png",
        "category": "Sports",
        "rating": 4.5,
        "stock": 35,
        "featured": False,
    },
    {
        "name": "Insulated Water Bottle",
        "price": 29.99,
        "original_price": 39.99,
        "description": "Double-wall vacuum insulated water bottle. Keeps drinks cold for 24 hours or hot for 12 hours. BPA-free, leak-proof lid.",
        "image_url": "/static/images/sports/insulated_water_bottle.png",
        "category": "Sports",
        "rating": 4.6,
        "stock": 45,
        "featured": False,
    },
    {
        "name": "Resistance Bands Set",
        "price": 24.99,
        "original_price": 34.99,
        "description": "Set of 5 resistance bands with different tension levels, door anchor, handles, and ankle straps. Complete home workout kit.",
        "image_url": "/static/images/sports/resistance_bands_set.png",
        "category": "Sports",
        "rating": 4.4,
        "stock": 50,
        "featured": False,
    },
    {
        "name": "Adjustable Dumbbells Set",
        "price": 199.99,
        "original_price": 279.99,
        "description": "Space-saving adjustable dumbbells from 5 to 52.5 lbs. Quick-change weight system for efficient home workouts.",
        "image_url": "/static/images/sports/adjustable_dumbbells_set.png",
        "category": "Sports",
        "rating": 4.8,
        "stock": 12,
        "featured": True,
    },
    {
        "name": "Sports Gym Bag",
        "price": 44.99,
        "original_price": 59.99,
        "description": "Spacious gym bag with shoe compartment, wet pocket, and padded shoulder strap. Water-resistant nylon construction.",
        "image_url": "/static/images/sports/sports_gym_bag.png",
        "category": "Sports",
        "rating": 4.3,
        "stock": 30,
        "featured": False,
    },
    # ─── Perfumes ────────────────────────────────────────
    {
        "name": "Midnight Rose Eau de Parfum",
        "price": 89.99,
        "original_price": 129.99,
        "description": "An enchanting floral fragrance with top notes of rose and bergamot, heart notes of jasmine, and a warm amber base. Long-lasting 8-hour wear. 100ml.",
        "image_url": "/static/images/perfumes/midnight_rose_eau_de_parfum.png",
        "category": "Perfumes",
        "rating": 4.8,
        "stock": 20,
        "featured": True,
    },
    {
        "name": "Ocean Breeze Cologne",
        "price": 69.99,
        "original_price": 99.99,
        "description": "Fresh and invigorating cologne with marine accord, citrus zest, and driftwood base. Perfect for everyday wear. 75ml.",
        "image_url": "/static/images/perfumes/ocean_breeze_cologne.png",
        "category": "Perfumes",
        "rating": 4.5,
        "stock": 25,
        "featured": True,
    },
    {
        "name": "Velvet Oud Intense",
        "price": 149.99,
        "original_price": 199.99,
        "description": "Luxurious oriental fragrance featuring rare oud wood, saffron, and dark vanilla. Sophisticated and mysterious. 100ml.",
        "image_url": "/static/images/perfumes/velvet_oud_intense.png",
        "category": "Perfumes",
        "rating": 4.9,
        "stock": 10,
        "featured": True,
    },
    {
        "name": "Citrus Garden EDT",
        "price": 54.99,
        "original_price": 74.99,
        "description": "Light and refreshing eau de toilette with notes of lemon, grapefruit, green tea, and white musk. Perfect for spring and summer. 100ml.",
        "image_url": "/static/images/perfumes/citrus_garden_edt.png",
        "category": "Perfumes",
        "rating": 4.4,
        "stock": 30,
        "featured": False,
    },
    {
        "name": "Golden Amber Perfume",
        "price": 119.99,
        "original_price": 159.99,
        "description": "Warm and sensual fragrance with notes of amber, vanilla orchid, sandalwood, and a whisper of cinnamon. Unisex. 75ml.",
        "image_url": "/static/images/perfumes/golden_amber_perfume.png",
        "category": "Perfumes",
        "rating": 4.7,
        "stock": 15,
        "featured": False,
    },
    {
        "name": "Wild Lavender Mist",
        "price": 39.99,
        "original_price": None,
        "description": "Calming body mist with French lavender, chamomile, and soft cotton notes. Gentle and soothing everyday fragrance. 150ml.",
        "image_url": "/static/images/perfumes/wild_lavender_mist.png",
        "category": "Perfumes",
        "rating": 4.3,
        "stock": 40,
        "featured": False,
    },
]


def seed():
    """Seed database with products using local images."""
    with app.app_context():
        db.create_all()
        # Clear existing products and re-seed
        Product.query.delete()
        db.session.commit()

        for data in PRODUCTS:
            product = Product(**data)
            db.session.add(product)
        db.session.commit()
        print(f"SUCCESS: Seeded {len(PRODUCTS)} products with local images successfully!")


if __name__ == '__main__':
    seed()
